ci_service: travis_ci
coverage_service: cobertura_xml
workspace: vl-ios.xcworkspace
xcodeproj: vl-ios.xcodeproj
scheme: vl-ios
source_directory: vl-ios
output_directory: test_results/xml_report
ignore:
  - vl-iosTests/*
