language: objective-c
osx_image: xcode10.2

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=vl-ios.xcworkspace
  - FRAMEWORK_SCHEME="vl-ios"
  - SDK=iphonesimulator12.2
  - RUN_TESTS="YES"
  - POD_LINT="NO"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone XS"
    - DESTINATION="OS=11.4,name=iPhone X"

install:
- bundle install

script: 
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

# Build Framework in Debug and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$FRAMEWORK_SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=YES build | xcpretty;
    fi

after_success:
  - slather
  - bash <(curl -s https://codecov.io/bash) -f test_results/xml_report/cobertura.xml -X coveragepy -X gcov -X xcode
